#
# Copyright, 2019, CleverDATA, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

language: java

install: true

sudo: false

dist: xenial

jdk: openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

git:
  depth: false

script:
  - |-
      echo Prepare
      export BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
      export BRANCH_NAME="${TRAVIS_BRANCH}"
  - |-
      echo Release Prepare
      if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
        ./gradlew --console=plain --stacktrace dmpkitReleaseInit
      fi
  - |-
      echo Test
      ./gradlew --console=plain --stacktrace test
  - |-
      echo Integration Test
      ./gradlew --console=plain --stacktrace itest
  - |-
      echo Code Quality
      ./gradlew --console=plain --stacktrace check -x test -x itest
  - |-
      echo Build
      ./gradlew --console=plain --stacktrace jar
  - |-
      echo Release Finish
      ./gradlew --console=plain --stacktrace dmpkitReleaseFinish
      ./gradlew --console=plain --stacktrace publish
